### ISSUE TITLE
Unable to run the CH_parameterization example

### ISSUE THREAD

**Issue by Anshuman5** [pekkosk/hotbit#14]
Dear pekkosk,

I am getting the below error while using the latest example from HOTBIT:

DeprecationWarning: Please stop using old trajectory files!
Convert to the new future-proof format like this:

    $ python -m ase.io.trajectory CH-.traj
---------------------------------------------------------
After downloading the code using :- git clone https://github.com/pekkosk/hotbit.git
and modifying the environment variables, I was able to run the tests without any error.
I have ase-15.0 code installed. 
I was not able run 'Quench benzene molecule (benzene.py) ' from the example.
This gave me the following error
    from ase.data.molecules import molecule
ImportError: cannot import name molecule.
I changed from ase.data.molecules import molecule to from ase.structure import molecule
and this works fine. 
I am wondering if we need to modify the example CH.py code along with the source code to run this? 
Please let me which version of ase should I use to run HOTBIT.
Currently, I am using ase-15.0
Update:: I had to modify fitting.py code to use Trajectory instead of PickleTrajectory and the program runs without any error.

Best Regards,
Anshuman

**Comment by pekkosk** [comment]
Sorry for late reply. What do you mean by ase-15.0; do you mean ase-3.15.0? Is it now working?

**Comment by Anshuman5** [comment]
Thanks a lot for replying.
We are facing some issues in generating the trajectory file using ASE for replusion fitting. We tried nwchem calculator with ASE to get the DFT energies. The energy values from our DFT calculation is very large compared to the ones used in the example file. Here, we tried generating traj file for CH-. Please find the python script attached along with the trajectory file that it generates.
[CH-.zip](https://github.com/pekkosk/hotbit/files/1541102/CH-.zip).  
The energy values that we got for DFT calculation is very off from the one used in the CH-.traj file in CH_parameterization example.

**Comment by pekkosk** [comment]
Do you mean the absolute energy values? They can be anything, depending on the calculator-dependent convention for the zero energy. You need to calculate atom energies also and then cohesion energy.

**Comment by Anshuman5** [comment]
Yes, I meant the energy values(units of eV) in the trajectory files generated from the DFT calculation.Many thanks for the clarification.
