### ISSUE TITLE
CC repulsion fitting with diamond

### ISSUE THREAD

**Issue by sally008** [pekkosk/hotbit#18]
[diamond.txt](https://github.com/pekkosk/hotbit/files/1675668/diamond.txt)
Hello again,

I have succeeded in creating a trajectory file for graphene and was able to use the "append_energy_curve" function for this file without any errors. However, when I try to do the same for my diamond trajectory, I get the following error : 

AssertionError: Distance between atoms 0 and 1 is only 0.0000 Bohr

However, in my files none of the atoms are abnormally close together. Do you have any idea why I am getting this error?

**Comment by pekkosk** [comment]
This error comes -- as you also write -- that atoms are abnormally close together. Whatever the reason, the error is (presumably) in the Atoms-object.
