### ISSUE TITLE
Free atom on-site energies for Au

### ISSUE THREAD

**Issue by Anshuman5** [pekkosk/hotbit#19]
Hi ,

While using the scalar relativistic KSAllelectron calculation with gold (Au) gives the on-site valence energies as :

6s: -0.222837407
6p: -0.032527285
5d: -0.261806241

which is significantly different from the valence energies available in AuAu_Parameterization examples.
 
6s:  -0.2149
6p: -0.0096
5d: -0.2537

What parameter should I use to get the energies match the above values?
I tried changing the amount of electrons being added/removed from the 6s/6p orbitals but it does not work.

Best Regards,
Anshuman

**Comment by pekkosk** [comment]
The example was made quickly and it's possible the pre-made Au.elm-file was made with non-optimized parameters. Your numbers above ought to be reliable.
