### ISSUE TITLE
How to reproduce Hubbard parameters

### ISSUE THREAD

**Issue by junoshiki** [pekkosk/hotbit#23]
Dear administrator

When I tested Au parametrization example, I found that the Hubbard or orbital energies of Au I calculated is different from the values in default Au.elm (in /hotbit/param/fixed_parameters).
In this calculation, I used KSAllElectron with Scalar Relativistic correction. 

I cannot reproduce exactly orbital energies and Hubbard parameters of not only Au but also other elements.

For example,  in default C.elm file, the energies of 2p and 2s are
epsilon_2s=-0.4988 
epsilon_2p=-0.1974 

However, the values I calculated (using KSAllElectron or IP_EA without confinement or Scalar Relativistic Correction) are
epsilon_2s= -0.500675
epsilon_2p= -0.199259

How can I reproduce these values exactly?

**Comment by pekkosk** [comment]
The C parameters, as noted in the comments, are not calculated by KSAllElectron (or Hotbit), but they are from Porezag’s and others’ original work. There is 51 meV constant shift, whose origin is unknown for me. The Hubbard U in most parametrizations is not adopted from calculated ionization energies and electron affinities, but tabulated (experimental) ones.

**Comment by junoshiki** [comment]
Dear, Dr. Koskinen,

Thank you for your instruction.
It really helped.

Best regards,

JunOshiki
