### ISSUE TITLE
Plenty of Warnings during the test

### ISSUE THREAD

**Issue by hsulab** [pekkosk/hotbit#25]
I used miniconda3, ase 3.19 and gcc 4.8.5 to compile hotbit.
Few warnings and a failure during the test.
Can you help me with this?
![image](https://user-images.githubusercontent.com/22236986/82503890-07b09e80-9af2-11ea-96ce-c0547fa36272.png)

**Comment by pekkosk** [comment]
Some parts of the code are admittedly deprecated and ought to be updated. However, for normal use, these warnings should not be critical (apart from LR).

**Comment by hsulab** [comment]
The linear response error is due to the incompatibility of old pylab. I changed few codes to get the correct results. So does the parameterization script.
