### ISSUE TITLE
ImportError: cannot import name Trajectory

### ISSUE THREAD

**Issue by anson8292** [pekkosk/hotbit#8]
Dear Pekkosk,

I downloaded and installed your code hotbit. When I run the test.py, there is an error as "ImportError: cannot import name Trajectory". Could you tell me how to deal with it? Thanks.

Best regards,
Yunsong Li

**Comment by pekkosk** [comment]
Which ASE version do you have?



13.3.2017 21.46 "anson8292" <notifications@github.com> kirjoitti:

**Comment by anson8292** [comment]
Dear Pekkosk,
It's ASE3.8.1. Thnaks.
Yunsong

**Comment by ajjackson** [comment]
Please try a recent version of ASE, such as that obtained with `pip install --user ase`. Hotbit was recently updated to support some of the major changes in ASE.
